import type { Metadata } from "next";
import { Noto_Sans_KR, Fredoka } from "next/font/google";
import { Providers } from "./providers";
import ConditionalHeader from "@/components/ConditionalHeader";
import "./globals.css";
import { StyledComponentsRegistry } from "@/lib/styled-components-registry";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans",
});

const baloo2 = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKr.variable} ${baloo2.variable} antialiased`}>
        <StyledComponentsRegistry suppressHydrationWarning>
          <Providers>
            <ConditionalHeader />
            {children}
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
